#!/bin/bash


function getFlavour
{

	lliurex_version=$(lliurex-version)
	IFS=","
	read -a flavours <<< "$lliurex_version"

	for item in "${flavours[@]}";
	do
		if [[ $item == *"server"* ]];then
			version="server"
			break
		elif [[ $item == *"client"* ]];then
			version="client"
			break
		elif [[ $item == *"desktop"* ]];then
			version="standalone"
		fi
	done

	echo $version

}

ACTION="$1"
PKG_CLIENT_EXCLUSIVE="cdc-mapper-config-client"
PKG_STANDALONE_EXCLUSIVE="cdc-mapper-config-localhost"
PKG_SERVER_EXCLUSIVE="cdc-mapper-config-localhost-server"

shift

PACKAGE_LIST=$@



case $ACTION in

	preInstall)

		version=$(getFlavour)

		for ix in $PACKAGE_LIST
		do
			if [[ "$ix" == "$PKG_CLIENT_EXCLUSIVE" ]];then
				if [[ "$version" != "client" ]];then
					echo "ERROR: You are trying to install the CDC setup for client on a server or desktop computer"
					exit 1
				fi
			elif [[ "$ix" == "$PKG_STANDALONE_EXCLUSIVE" ]];then
				if [[ "$version" != "standalone" ]];then
					echo "ERROR: You are trying to install the CDC setup for desktop on a server or client computer"
					exit 1
				fi
			elif [[ "$ix" == "$PKG_SERVER_EXCLUSIVE" ]];then
				if [[ "$version" != "server" ]];then
					echo "ERROR: You are trying to install the CDC setup for server on a desktop or client computer"
					exit 1
				fi
			fi
		done

	;;

	remove)
		match=0
		for ix in $PACKAGE_LIST
		do
			apt-get remove -y $ix
			TEST=$( dpkg-query -s $ix 2> /dev/null| grep Status | cut -d " " -f 4 )
			if [ "$TEST" == 'installed' ];then
				match+=1
			fi
		done

		if [ "$match" -gt 0 ];then
			exit 1
		fi
				
	;;	
esac